---
- hosts: node
  remote_user: root
  vars_files:
    - var.yaml

  tasks:
    - name: start_node
      shell: mfschunkserver start; echo "mfschunkserver start" >> /etc/rc.local; chmod 755 /etc/rc.d/rc.local

    - name: start_client
      shell: mfsmount -H {{master}} {{client_dir}}; echo "mfsmount -H {{master}} {{client_dir}}" >> /etc/rc.local
